// listee-106/reactjs/src/components/blog/BlogList/index.jsx
import React from "react";
import { ProfileAvatar12, ProfileAvatar13, ProfileAvatar14, bloglistingimg_1, bloglistingimg_2, bloglistingimg_3, category_icon, details_icon } from "../../imagepath";
import { Link, useLocation } from "react-router-dom";
import Footer from "../../home/footer/Footer";
import StickyBox from "react-sticky-box";
import Header from "../../home/header";



const BlogList = () => {
    const parms=useLocation().pathname
    return (
        <>
            <Header parms={parms}/>
            {/* Breadscrumb Section */}
            <div className="breadcrumb-bar">
                <div className="container">
                    <div className="row align-items-center text-center">
                        <div className="col-md-12 col-12">
                            <h2 className="breadcrumb-title">Listings-Blog</h2>
                            <nav aria-label="breadcrumb" className="page-breadcrumb">
                                <ol className="breadcrumb">
                                    <li className="breadcrumb-item">
                                        <Link to="/index">Home</Link>
                                    </li>
                                    <li className="breadcrumb-item active" aria-current="page">
                                        Blog
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            {/* /Breadscrumb Section */}
            {/* Blog List */}
            <div className="bloglisting">
                <div className="container">
                    <div className="row">
                        <div className="col-lg-8">
                            <div className="bloglist-widget">
                                <div className="blog grid-blog">
                                    <div className="blog-image">
                                        <Link to="/blog-details">
                                            <img
                                                className="img-fluid"
                                                src={bloglistingimg_1}
                                                alt="Post Image"
                                            />
                                        </Link>
                                    </div>
                                    <div className="blog-content">
                                        <p className="blog-category">
                                            <Link to="#">
                                                <span>Health</span>
                                            </Link>
                                            <Link to="#">
                                                <span>Care</span>
                                            </Link>
                                        </p>
                                        <ul className="entry-meta meta-item">
                                            <li>
                                                <div className="post-author">
                                                    <div className="post-author-img">
                                                        <img
                                                            src={ProfileAvatar13}
                                                            alt="author"
                                                        />
                                                    </div>
                                                    <Link to="#">
                                                        <span> Mary </span>
                                                    </Link>
                                                </div>
                                            </li>
                                            <li className="date-icon">
                                                <i className="fa-solid fa-calendar-days" /> October 6, 2022
                                            </li>
                                        </ul>
                                        <h3 className="blog-title">
                                            <Link to="/blog-details">
                                                The Best SPA Salons For Your Relaxation
                                            </Link>
                                        </h3>
                                        <p className="mb-0">
                                            Contrary to popular belief, Lorem Ipsum is not simply random
                                            text. It has roots in a piece of classical Latin literature
                                            from 45 BC, making it over 2000 years old. Richard
                                        </p>
                                        <div className="viewlink">
                                            <Link to="/blog-details">
                                                View Details <i className="feather-arrow-right" />
                                            </Link>
                                        </div>
                                    </div>
                                </div>
                                <div className="blog grid-blog">
                                    <div className="blog-image">
                                        <Link to="/blog-details">
                                            <img
                                                className="img-fluid"
                                                src={bloglistingimg_2}
                                                alt="Post Image"
                                            />
                                        </Link>
                                    </div>
                                    <div className="blog-content">
                                        <p className="blog-category">
                                            <Link to="#">
                                                <span>Health</span>
                                            </Link>
                                            <Link to="#">
                                                <span>Care</span>
                                            </Link>
                                        </p>
                                        <ul className="entry-meta meta-item">
                                            <li>
                                                <div className="post-author">
                                                    <div className="post-author-img">
                                                        <img
                                                            src={ProfileAvatar14}
                                                            alt="author"
                                                        />
                                                    </div>
                                                    <Link to="#">
                                                        {" "}
                                                        <span> Barbara </span>
                                                    </Link>
                                                </div>
                                            </li>
                                            <li className="date-icon">
                                                <i className="fa-solid fa-calendar-days" /> October 9, 2022
                                            </li>
                                        </ul>
                                        <h3 className="blog-title">
                                            <Link to="/blog-details">Great Business Tips in 2022</Link>
                                        </h3>
                                        <p className="mb-0">
                                            Contrary to popular belief, Lorem Ipsum is not simply random
                                            text. It has roots in a piece of classical Latin literature
                                            from 45 BC, making it over 2000 years old. Richard
                                        </p>
                                        <div className="viewlink">
                                            <Link to="/blog-details">
                                                View Details <i className="feather-arrow-right" />
                                            </Link>
                                        </div>
                                    </div>
                                </div>
                                <div className="blog grid-blog">
                                    <div className="blog-image">
                                        <Link to="/blog-details">
                                            <img
                                                className="img-fluid"
                                                src={bloglistingimg_3}
                                                alt="Post Image"
                                            />
                                        </Link>
                                    </div>
                                    <div className="blog-content">
                                        <p className="blog-category">
                                            <Link to="#">
                                                <span>Health</span>
                                            </Link>
                                            <Link to="#">
                                                <span>Care</span>
                                            </Link>
                                        </p>
                                        <ul className="entry-meta meta-item">
                                            <li>
                                                <div className="post-author">
                                                    <div className="post-author-img">
                                                        <img
                                                            src={ProfileAvatar12}
                                                            alt="author"
                                                        />
                                                    </div>
                                                    <Link to="#">
                                                        {" "}
                                                        <span> Darryl </span>
                                                    </Link>
                                                </div>
                                            </li>
                                            <li className="date-icon">
                                                <i className="fa-solid fa-calendar-days" /> October 7, 2022
                                            </li>
                                        </ul>
                                        <h3 className="blog-title">
                                            <Link to="/blog-details">
                                                8 Amazing Tricks About Business
                                            </Link>
                                        </h3>
                                        <p className="mb-0">
                                            Contrary to popular belief, Lorem Ipsum is not simply random
                                            text. It has roots in a piece of classical Latin literature
                                            from 45 BC, making it over 2000 years old. Richard
                                        </p>
                                        <div className="viewlink">
                                            <Link to="/blog-details">
                                                View Details <i className="feather-arrow-right" />
                                            </Link>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {/*Pagination*/}
                            <div className="blog-pagination">
                                <nav>
                                    <ul className="pagination">
                                        <li className="page-item previtem">
                                            <Link className="page-link" to="#">
                                                <i className="fas fa-regular fa-arrow-left" /> Prev
                                            </Link>
                                        </li>
                                        <li className="justify-content-center pagination-center">
                                            <div className="pagelink">
                                                <ul>
                                                    <li className="page-item">
                                                        <Link className="page-link" to="#">
                                                            1
                                                        </Link>
                                                    </li>
                                                    <li className="page-item active">
                                                        <Link className="page-link" to="#">
                                                            2 <span className="visually-hidden">(current)</span>
                                                        </Link>
                                                    </li>
                                                    <li className="page-item">
                                                        <Link className="page-link" to="#">
                                                            3
                                                        </Link>
                                                    </li>
                                                    <li className="page-item">
                                                        <Link className="page-link" to="#">
                                                            ...
                                                        </Link>
                                                    </li>
                                                    <li className="page-item">
                                                        <Link className="page-link" to="#">
                                                            14
                                                        </Link>
                                                    </li>
                                                </ul>
                                            </div>
                                        </li>
                                        <li className="page-item nextlink">
                                            <Link className="page-link" to="#">
                                                Next <i className="fas fa-regular fa-arrow-right" />
                                            </Link>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                            {/*/Pagination*/}
                        </div>
                        <div className="col-lg-4 theiaStickySidebar">
                            <StickyBox>
                                <div className="rightsidebar blogsidebar">
                                    <div className="card">
                                        <h4>
                                            <img src={details_icon} alt="details-icon" />{" "}
                                            Filter
                                        </h4>
                                        <div className="filter-content looking-input form-group">
                                            <input
                                                type="text"
                                                className="form-control"
                                                placeholder="To Search type and hit enter"
                                            />
                                        </div>
                                    </div>
                                    <div className="card">
                                        <h4>
                                            <img src={category_icon} alt="details-icon" />{" "}
                                            Categories
                                        </h4>
                                        <ul className="blogcategories-list">
                                            <li>
                                                <Link to="#">Accept Credit Cards</Link>
                                            </li>
                                            <li>
                                                <Link to="#">Smoking Allowed</Link>
                                            </li>
                                            <li>
                                                <Link to="#">Bike Parking</Link>
                                            </li>
                                            <li>
                                                <Link to="#">Street Parking</Link>
                                            </li>
                                            <li>
                                                <Link to="#">Wireless Internet</Link>
                                            </li>
                                            <li>
                                                <Link to="#">Pet Friendly</Link>
                                            </li>
                                        </ul>
                                    </div>
                                    <div className="card tags-widget">
                                        <h4>
                                            <i className="feather-tag" /> Tags
                                        </h4>
                                        <ul className="tags">
                                            <li>Travelling </li>
                                            <li>Art </li>
                                            <li>Vacation </li>
                                            <li>Tourism </li>
                                            <li>Culture </li>
                                            <li>Lifestyle </li>
                                            <li>Travelling </li>
                                            <li>Art </li>
                                            <li>vacation </li>
                                            <li>Tourism </li>
                                            <li>Culture </li>
                                        </ul>
                                    </div>
                                    <div className="card">
                                        <h4>
                                            <i className="feather-tag" /> Article
                                        </h4>
                                        <div className="article">
                                            <Link to="/blog-details" className="articleimg-1">
                                                <ul>
                                                    <li>
                                                        <h6>Great Business Tips in 2022</h6>
                                                    </li>
                                                    <li className="date-icon">
                                                        <i className="fa-solid fa-calendar-days" /> October 6,
                                                        2022
                                                    </li>
                                                </ul>
                                            </Link>
                                        </div>
                                        <div className="article">
                                            <Link to="/blog-details" className="articleimg-2">
                                                <ul>
                                                    <li>
                                                        <h6>Excited News About Fashion.</h6>
                                                    </li>
                                                    <li className="date-icon">
                                                        <i className="fa-solid fa-calendar-days" /> October 9,
                                                        2022
                                                    </li>
                                                </ul>
                                            </Link>
                                        </div>
                                        <div className="article">
                                            <Link to="/blog-details" className="articleimg-3">
                                                <ul>
                                                    <li>
                                                        <h6>8 Amazing Tricks About Business</h6>
                                                    </li>
                                                    <li className="date-icon">
                                                        <i className="fa-solid fa-calendar-days" /> October 10,
                                                        2022
                                                    </li>
                                                </ul>
                                            </Link>
                                        </div>
                                    </div>
                                </div>
                            </StickyBox>
                        </div>
                    </div>
                </div>
            </div>
            {/* /Blog List */}
            <Footer />
        </>

    );
}
export default BlogList;

// listee-106/vuejs/src/views/pages/blog/blog-list/BlogList.vue
<template>
    <!-- Blog List -->
		<div class="bloglisting">
		    <div class="container">
		        <div class="row">
			        <div class="col-lg-8">
						<div class="bloglist-widget">
						    <div class="blog grid-blog" v-for="item in BlogList" :key="item.id">
								<div class="blog-image">
									<router-link to="blog-details"><img class="img-fluid" :src="require(`../../../../assets/img/blog/${item.img1}`)" alt="Post Image"></router-link>
								</div>
							   	<div class="blog-content">
									<p class="blog-category">
									   <a href="javascript:void(0)"><span>Health</span></a><a href="javascript:void(0)"><span>Care</span></a>
									</p>
									<ul class="entry-meta meta-item">
										<li>
											<div class="post-author">
											     <div class="post-author-img">
										       	       <img :src="require(`../../../../assets/img/profiles/${item.img2}`)" alt="author">
												 </div>
											<a href="javascript:void(0)"><span> {{ item.name }} </span></a>
											</div>
										</li>
										<li class="date-icon"><i class="fa-solid fa-calendar-days"></i> {{ item.date }}</li>
									</ul>
									<h3 class="blog-title"><router-link to="blog-details">{{ item.title }}</router-link></h3>
									<p class="mb-0">{{ item.content }}</p>
									<div class="viewlink"><router-link to="blog-details">{{ item.button }}<i class="feather-arrow-right"></i></router-link></div>
								</div>
							</div>
						</div>
						                   					   
                         <!--Pagination--> 
						<div class="blog-pagination">
						    <nav>
							    <ul class="pagination">
								    <li class="page-item previtem">
										<a class="page-link" href="#"><i class="fas fa-regular fa-arrow-left"></i> Prev</a>
									</li>
									<li class="justify-content-center pagination-center"> 
										<div class="pagelink">
										   <ul>
												<li class="page-item">
													<a class="page-link" href="#">1</a>
												</li>
												<li class="page-item active">
													<a class="page-link" href="#">2 <span class="visually-hidden">(current)</span></a>
												</li>
												<li class="page-item">
													<a class="page-link" href="#">3</a>
											   </li>
											   <li class="page-item">
													<a class="page-link" href="#">...</a>
											   </li>
											   <li class="page-item">
													<a class="page-link" href="#">14</a>
											   </li>
											</ul>
									    </div>													
									</li>													
									<li class="page-item nextlink">
										<a class="page-link" href="#">Next <i class="fas fa-regular fa-arrow-right"></i></a>
									</li>
								</ul>
							</nav>
						</div>
						<!--/Pagination-->						  

				    </div>
				    <div class="col-lg-4 theiaStickySidebar">
						<div class="stickysidebar">
				        <div class="rightsidebar blogsidebar">
						    <div class="card">
						      <h4><img src="../../../../assets/img/details-icon.svg" alt="details-icon"> Filter</h4>
						      <div class="filter-content looking-input form-group">
								  <input type="text" class="form-control" placeholder="To Search type and hit enter">
							  </div>
							</div>
							<div class="card">
							    <h4><img src="../../../../assets/img/category-icon.svg" alt="details-icon"> Categories</h4>
							    <ul class="blogcategories-list">
							      <li><a href="javascript:void(0)">Accept Credit Cards</a></li>
							      <li><a href="javascript:void(0)">Smoking Allowed</a></li>
							      <li><a href="javascript:void(0)">Bike Parking</a></li>
							      <li><a href="javascript:void(0)">Street Parking</a></li>
							      <li><a href="javascript:void(0)">Wireless Internet</a></li>
							      <li><a href="javascript:void(0)">Pet Friendly</a></li>										   
							    </ul>
							</div>
							<div class="card tags-widget">
							    <h4><i class="feather-tag"></i> Tags</h4>
								<ul class="tags">
								   <li>Travelling </li>
								   <li>Art </li>
								   <li>Vacation </li>
								   <li>Tourism </li>
								   <li>Culture </li>
								   <li>Lifestyle </li>
								   <li>Travelling </li>
								   <li>Art </li>
								   <li>vacation </li>
								   <li>Tourism </li>
								   <li>Culture </li>								
								</ul>
							</div>
							<div class="card">
							    <h4><i class="feather-tag"></i> Article</h4>
								<div class="article">
								    <router-link to="blog-details" class="articleimg-1">
								        <ul>
										   <li><h6>Great Business Tips in 2022</h6></li>
										   <li class="date-icon"><i class="fa-solid fa-calendar-days"></i> October 6, 2022</li> 
									   </ul>
								    </router-link>								 
								</div>
								<div class="article">
								    <router-link to="blog-details" class="articleimg-2">
								       <ul>
										   <li><h6>Excited News About Fashion.</h6></li>
										   <li class="date-icon"><i class="fa-solid fa-calendar-days"></i> October 9, 2022</li> 
									   </ul>
								    </router-link>								 
								</div>
								<div class="article">
								    <router-link to="blog-details" class="articleimg-3">
								       <ul>
										   <li><h6>8 Amazing Tricks About Business</h6></li>
										   <li class="date-icon"><i class="fa-solid fa-calendar-days"></i> October 10, 2022</li> 
									   </ul>
								    </router-link>								 
								</div>
							</div>
						</div>
					</div>
				</div>
				</div>
			</div>				   
		</div>			
		<!-- /Blog List -->
</template>

<script>
import BlogList from '../../../../assets/json/blogList.json'
	export default {
		data() {
			return {
				BlogList: BlogList
			};
		},
	};
</script>
